{
 "title": "Tomcat Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(tomcat_session_active_total, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(tomcat_session_active_total{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Runtime Vendor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  {
   "title": "JVM Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{runtime}}"
    }
   ]
  },
  {
   "title": "JVM Runtime Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "JVM Uptime Hrs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(time()-(process_start_time_seconds{instance=\"$node\",job=\"$job\"})) /60/60"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "stat",
   "description": "The number of classes that are currently loaded in the JVM",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Application Contexts Started",
   "type": "graph",
   "description": "Indication if the lifecycle state of this context is STARTED",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_context_state_started{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Runs /sec over 1 min",
   "type": "graph",
   "description": "Count of JVM garbage collector runs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=\"$node\",job=\"$job\"}[1m])*100",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time in sec over 1 min",
   "type": "graph",
   "description": "Time spent in a given JVM garbage collector in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$node\",job=\"$job\"}[1m])*100",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Avg Time (ms) / GC 1 minute rate",
   "type": "graph",
   "description": "JVM garbage run times",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(jvm_gc_collection_seconds_sum{instance=\"$node\",job=\"$job\"}[1m])*100 / rate(jvm_gc_collection_seconds_count{instance=\"$node\",job=\"$job\"}[1m])*100)",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "JVM Threads Started Total",
   "type": "stat",
   "description": "Started thread count of a JVM",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_started_total{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Threads Current",
   "type": "stat",
   "description": "Current thread count of a JVM",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Threads Peak",
   "type": "stat",
   "description": "Peak thread count of a JVM",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_peak{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Threads Deadlocked",
   "type": "stat",
   "description": "Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Thread State",
   "type": "graph",
   "description": "Current count of threads by state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Heap Max (MB)",
   "type": "stat",
   "description": "Max (bytes) of a given JVM memory area.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{instance=\"$node\",job=\"$job\",area=\"heap\"} /1024/1024"
    }
   ]
  },
  {
   "title": "NonHeap Max (MB)",
   "type": "stat",
   "description": "Max (bytes) of a given JVM memory area.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{instance=\"$node\",job=\"$job\",area=\"nonheap\"} /1024/1024"
    }
   ]
  },
  { "title": "Total JVM Memory", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 54 } },
  {
   "title": "JVM Total Memory Committed (MB)",
   "type": "graph",
   "description": "Committed (bytes) of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "JVM Total Memory Used (MB)",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{area}}"
    }
   ]
  },
  { "title": "JVM Memory Pool", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 63 } },
  {
   "title": "JVM Memory Pool Committed (MB)",
   "type": "graph",
   "description": "Committed bytes of a given JVM memory pool.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Used (MB)",
   "type": "graph",
   "description": "Used bytes of a given JVM memory pool.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Max (MB)",
   "type": "graph",
   "description": "Max bytes of a given JVM memory pool.\n",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=\"$node\",job=\"$job\"} /1024/1024",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "Tomcat Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Sessions Created Total /sec over 1 min",
   "type": "graph",
   "description": "Number of sessions created",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_created_total{instance=\"$node\",job=\"$job\"}[1m])*100",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Active Total /sec over 1 min",
   "type": "graph",
   "description": "Number of active sessions",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_active_total{instance=\"$node\",job=\"$job\"}[1m])*100",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Rejected Total /sec over 1 min",
   "type": "graph",
   "description": "Number of sessions rejected due to maxActive being reached",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_rejected_total{instance=\"$node\",job=\"$job\"}[1m]) *100",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Expired Total /sec over 1 min",
   "type": "graph",
   "description": "Number of sessions that expired",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_expired_total{instance=\"$node\",job=\"$job\"}[1m])*100",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Alive Time Max over 5 min (in seconds)",
   "type": "graph",
   "description": "Maximum time an expired session had been alive",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_alivetime_seconds_max{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "Sessions Alive Time Avg  /sec over 5 min",
   "type": "graph",
   "description": "Average time an expired session had been alive",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_session_alivetime_seconds_avg{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{context}}"
    }
   ]
  },
  { "title": "Tomcat Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Tomcat Connections Active Max",
   "type": "graph",
   "description": "Maximum number of concurrent connections served by this pool.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_connections_active_max{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tomcat Connections Active Total",
   "type": "graph",
   "description": "Number of connections served by this pool.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_connections_active_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Tomcat Request Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Requests /sec per 5 minutes",
   "type": "graph",
   "description": "The number of request served by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_request_count{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Request Errors /sec per 5 minutes",
   "type": "graph",
   "description": "The number of error request served by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_error_count{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Percent Errors/Requests",
   "type": "graph",
   "description": "Rate of errors compared to total requests for the request processor",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tomcat_requestprocessor_error_count{instance=\"$node\",job=\"$job\"}[1m])) by (instance,name) \n/ sum(rate(tomcat_requestprocessor_request_count{instance=\"$node\",job=\"$job\"}[1m])) by (instance,name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Request Received Bytes (MB) /sec over 5 min",
   "type": "graph",
   "description": "Number of bytes received by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_received_bytes{instance=\"$node\",job=\"$job\"}[5m]) /1024/1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Request Sent Bytes (MB) /sec over 5 min",
   "type": "graph",
   "description": "Number of bytes sent by this request processor",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_requestprocessor_sent_bytes{instance=\"$node\",job=\"$job\"}[5m]) /1024/1024 ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}